[package]
name = "genetic_programming"
version = "0.1.0"
authors = ["limelier <limelier@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.7.0"
rand = "0.8.3"
rayon = "1.5.0"
indicatif = "0.17.6"
